name:                hou
version:             0.1.0.0
github:              "https://github.com/fixxxedpoint/hou"
license:             MIT
license-file:        LICENSE
author:              Łukasz Lachowski <l.lachowski@gmail.com>
maintainer:          Łukasz Lachowski <l.lachowski@gmail.com>
copyright:           2018 Łukasz Lachowski <l.lachowski@gmail.com>

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Type inference and type checking of SystemF terms
#                      using higher-order unification.
# category:            Theoretical Computer Science, Type Theory

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.md.

dependencies:
- base >= 4.7 && < 5
- array
- containers
- fmlist
- mtl
- random
- monad-gen

library:
  source-dirs: src
  exposed-modules:
    - Hou.HigherOrderUnification
    - Hou.InferenceUtils
    - Hou.LambdaPi
    - Hou.Levels
    - Hou.MixedPrefix
    - Hou.SystemF

executables:
  hou-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hou

tests:
  hou-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hou
    - hspec
